### ISSUE TITLE
[iOS-Feature] 트림 Step - UI

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#20]
## 💡 이슈 내용
- 트림 목록을 조회하고 선택할 수 있다.

## ✅ 상세 작업 내용
- [x] 트림 선택 화면 UI를 구현한다. - #175
- [x] 트림 목록 API를 받아와 목록을 보여준다. - #196
- [x] 트림을 선택하면 견적 요약에 반영된다. - #212
