### ISSUE TITLE
[iOS-Feature] 바디 타입 Step - UI

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#29]
## 💡 이슈 내용
- 바디 타입을 선택할 수 있다.

## ✅ 상세 작업 내용
- [x] 바디 타입 UI를 구현 - #184 
- [x] api 호출을 통해 선택 가능한 목록을 조회 - #201
- [x] 진입시 프리셋이 선택된다. - #212
## 📌 Reference
- []()
- []()
