### ISSUE TITLE
[iOS-Feature] 트림 Step - 세부사항

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#298]
## 💡 이슈 내용
- 트림 선택 화면에 대한 세부사항을 구현한다.

## ✅ 상세 작업 내용
- [x] 트림 변경시 이후 모든 단계의 선택이 초기화된다. - #393 
  - [x] 트림 선택시 이후 단계의 진행상황이 있을 경우, 모두 초기화 된다는 경고창이 뜬다. - #393 
  - [x] 없을 경우에는 아무런 이벤트가 발생하지 않는다.
- [x] 트림 선택시 견적서에 반영된다. - #356 
- [x] 진입시 이전에 선택했던 트림이 보여진다. - #356 
- [x] 트림 선택시 프리뷰가 보여진다 - #438
