### ISSUE TITLE
[Feature] 구동 방식 Step - 세부사항

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#300]
## 💡 이슈 내용
- 구동 방식 선택 Step에 대한 세부사항을 구현한다.

## ✅ 상세 작업 내용
- [x] 진입시 견적서에 반영된 `구동 방식`이 선택된 상태로 보여준다. - #429
- [x] 선택한 `구동 방식`이 견적서에 반영된다. - #429
- [x] `구동 방식` 선택시 미리보기를 보여준다. - #444 

## 📌 Reference
- []()
- []()
