### ISSUE TITLE
[Feature] 내장 색상 Step - 세부사항

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#302]
## 💡 이슈 내용
- 내장 색상 단계의 세부사항을 구현한다.

## ✅ 상세 작업 내용
- [x] 진입시 견적서에 반영된 `내장 색상`이 선택된 상태로 보여준다. - #429
- [x] `내장 색상` 선택시 견적서에 반영된다. - #429
- [x] `내장 색상` 선택시 미리보기를 보여준다. - #444 

## 📌 Reference
- []()
- []()
