### ISSUE TITLE
[Feature] 추가 옵션 Step - 세부사항

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#305]
## 💡 이슈 내용
- 추가 옵션 선택의 세부사항을 구현한다.

## ✅ 상세 작업 내용
- [x] 진입시 견적서에 반영된 `옵션`들이 선택된 상태로 보여준다. - #429

- [x] Cell을 `선택`시 상황을 처리한다. - #429
  - [x] 견적서의 selectedOptions에 반영된다.
  - [x] 견적서의 추가 옵션 가격에 반영된다.
- [x] Cell을 `고민해보기`시 견적서의 consideredOptions에 반영된다. - #429
- [x] Cell을 `선택 취소`시 상황을 처리한다. - #429
  - [x] 견적서의 selectedOptions/consideredOptions에서 제외된다.
  - [x] (selectedOptions의 경우) 견적서의 추가 옵션 가격에서 제외된다.

- [ ] 옵션 Cell 클릭시 상황에 따라 이벤트를 처리한다.
  - [x] 패키지 옵션일 경우, Cell에서 하위 옵션을 보여준다.
  - ~~[ ] 단일 옵션일 경우, 옵션의 세부사항에 대해서 팝업창으로 보여준다.~~ - #310 
  - [ ] 두 가지 상황에서 모두 미리보기 사진을 보여준다.
