### ISSUE TITLE
[iOS-Feature] 내장 색상 Step - UI

### ISSUE THREAD

**Issue by sseungmn** [softeerbootcamp-2nd/H5-MyCarMaster#34]
## 💡 이슈 내용
- 내장 색상을 변경할 수 있다.

## ✅ 상세 작업 내용
- [x] 내장 색상 UI를 구현 - #225 
- [x] api 호출을 통해 선택 가능한 목록을 조회 - #225 
- [x] 진입시 프리셋이 선택된다. - #225 

## 📌 Reference
- []()
- []()
